### ISSUE TITLE
Can members be static ?

### ISSUE THREAD

**Issue by davedawkins** [alfonsogarciacaro/Feliz.Engine#16]
Is it possible that we can make the HtmlEngine members static? We would still have the overloads, but then would be able to do an "open type HtmlEngine" to allow unqualified calls to `div` etc.

I don't mind doing the work, but don't want to attempt it if you know it won't work.

**Comment by alfonsogarciacaro** [comment]
Yes, this is an inconvenience compared to the original Feliz API. The main problem is we pass the implementation through the constructor arguments so we need a reference to the instance in the helper methods. If they are static we cannot access the `tag: sring -> nodes: Node seq -> Node` function. Maybe we could initialize the class statically but this would require mutating a global value and it's not ideal, and would also prevent having multiple implementations of the engines in the same app (in Feliz.Snabbdom there's an [alternative implementation of EventEngine](https://github.com/alfonsogarciacaro/Feliz.Snabbdom/blob/7b28ccbceebcc9b66a8cb67aab89b7ae9576dbfb/src/Feliz.Snabbdom/Feliz.Snabbdom.fs#L195-L198) to attach events to the document body).

Not sure if there's another workaround for this. Maybe with a type provider, but this could complicate things.

**Comment by davedawkins** [comment]
Yes, I remember now.
What happens if we try to pass the helper methods via a 'Helper type? The methods would have to be static on 'Helper but this works in most cases

**Comment by alfonsogarciacaro** [comment]
Interesting, I could make the following work:

```fsharp
type Helper =
    static member MakeNode(tag: string, nodes: int seq) = 0

let inline makeNode<'Helper, 'Node when 'Helper : (static member MakeNode : string * 'Node seq -> 'Node)> tag nodes =
    (^Helper : (static member MakeNode : string * 'Node seq -> 'Node) (tag, nodes))

type HtmlEngine<'Helper, 'Node when 'Helper : (static member MakeNode : string * 'Node seq -> 'Node)> =
    static member inline div(nodes: 'Node seq) =
        makeNode<'Helper,_> "div" nodes

type Html = HtmlEngine<Helper, int>

open type Html

let x = div []
```

It would require to inline everything which can have an impact in the bundle size (particularly when the helper methods contain more code), it complicates a bit the syntax and it won't be possible to use optional arguments when we want to pass additional behavior without breaking changes, but we can consider it if using `open type` is a requirement. I wish we could just open values ;)

**Comment by davedawkins** [comment]
I think it's worth trying, and measuring the code size difference for a reasonably sized project. 

It's not a hard requirement for `open type`, but something that can reduce noise in a project. Someone already commented that Sutil now requires the `Html.` 😀 

Is there value in converting Feliz.Engine into a generator so that we can (more) quickly generate and experiment with new strategies (see Feliz.Engine.Bulma for an example). This is something I can do that would let you generate a new API from the idea you present above, for example.

**Comment by alfonsogarciacaro** [comment]
A generator script could help. There are several differences now with the original Feliz, but maybe we can use the current Feliz.Engine version as the "original". Although if we want this to be used by someone at some point we would need to stop changing the API ;)

**Comment by davedawkins** [comment]
We're still in pre-release, it will never be easier than right now to get the API right. If you're sure we've nailed it then we should leave it, there's enough other stuff to do. However, if people do start using it, we'll want the best interop we can achieve between Feliz and Fable.React DSLs. It was interesting converting the SAFE client to Sutil, *very* easy, even with the non-static API.

Let's leave it for now. Feliz.Engine is awesome as it is. I wonder if "source generators" can do the equivalent of "open value".

**Comment by alfonsogarciacaro** [comment]
I do like qualifying the html elements to avoid namespace pollution and I think it will provide more flexibility in the future (STRP can get tricky sometimes), but I understand some people may be used to just quickly write `div`. Ok, let's leave it as is for now but keep the door open in case more people start asking for it :)
