### ISSUE TITLE
width vs height: consistency and noise reduction

### ISSUE THREAD

**Issue by davedawkins** [alfonsogarciacaro/Feliz.Engine#2]
Hi! 
This is how some of the code is looking while integrating Feliz.Engine

```
        Css.width 32
        Css.height.custom 24
```

1. Can width and height both have the same API?
2. I understand why height works that way, but is there any way to make it so that this works?

```
        Css.width 32
        Css.height 24

         // And also
        Css.height "inherit"  
        Css.height_.inherit
        Css.width "auto"
        Css.width_.auto
```

**Comment by alfonsogarciacaro** [comment]
You're right, having to use .custom for height (and others) is a very annoying. We couldn't mix method members and static modules as Feliz does. I don't mind using the underscore to distinguish members that give access to a subclass but then it starts looking to the underscore members we already discarded: Css.height_inherit 

What about just using additional members with camelCase?

Css.height 35
Css.heightInherit
Css.widthAuto

**Comment by alfonsogarciacaro** [comment]
I've quickly tried this and it looks like a good alternative that would also solve the issues we have with the sub-classes. The main con is it makes it harder to tell the property and the value apart but a good benefit is autocomplete offers you all the options at a quick glance without having to dot into the property:

![image](https://user-images.githubusercontent.com/8275461/109374808-66197180-78fb-11eb-8068-609364c2ac59.png)

What do you think @davedawkins? Would it be ok for you to use always camelCase without the dots?

**Comment by davedawkins** [comment]
Yes let's give it a try! Thank you!

**Comment by alfonsogarciacaro** [comment]
Done! I'll try to publish a new package later. Please give it a try and let me know what you think :+1:
