### ISSUE TITLE
Consistency of '.' properties

### ISSUE THREAD

**Issue by davedawkins** [alfonsogarciacaro/Feliz.Engine#3]
For display we say
```
    display.inlineBlock
```

For overflow we have to say
```
    overflow.overflow_scroll
```

Is it possible to say instead
```
    Css.overflow.scroll
```

**Comment by alfonsogarciacaro** [comment]
Yes, this seems to be a mistake when I was converting the sub classes, but please see also my comment in #2

**Comment by alfonsogarciacaro** [comment]
Fixed, thanks for pointing out the inconsistency!
