### ISSUE TITLE
Build Sutil app against copy of repo works, but building against package breaks view

### ISSUE THREAD

**Issue by davedawkins** [alfonsogarciacaro/Feliz.Engine#8]
Building against 1.0.0-beta-001

<img width="836" alt="image" src="https://user-images.githubusercontent.com/285421/109368313-a42d7b80-7890-11eb-8063-02100a6495b4.png">

**Comment by davedawkins** [comment]
Now it's broken against the repo copy too. False alarm, sorry

**Comment by davedawkins** [comment]
Do we need to push a newer package?

**Comment by davedawkins** [comment]
I think you may have fixed an issue in the latest repo that makes "px" the default unit, based on this devtools screenshot
<img width="167" alt="image" src="https://user-images.githubusercontent.com/285421/109368976-ba3c3b80-7892-11eb-9365-4eb8c3040352.png">

**Comment by alfonsogarciacaro** [comment]
Yes, it seems in some case the original API was not adding "px" to raw ints and floats. I hope I covered all the cases, please reopen if you find something. Please see also my comment here https://github.com/alfonsogarciacaro/Feliz.Engine/issues/4#issuecomment-787112637
